### ISSUE TITLE
Error after quest turn in

### ISSUE THREAD

**Issue by MarkKehn** [LudiusMaximus/Immersion_ExtraFade#1]
I was not in combat. I just turned in a quest and this error popped up:

1x Immersion_ExtraFade\main.lua:44: attempt to call method 'Show' (a boolean value)
[string "@Immersion_ExtraFade\main.lua"]:44: in function <Immersion_ExtraFade\main.lua:36>
[string "@Immersion_ExtraFade\main.lua"]:308: in function <Immersion_ExtraFade\main.lua:277>
[string "@Immersion_ExtraFade\main.lua"]:400: in function <Immersion_ExtraFade\main.lua:395>

Locals:
frame = QuickJoinToastButton {
 0 = <userdata>
 OnLeave = <function> defined @FrameXML\QuickJoinToast.lua:365
 OnPostShow = <function> defined =[C]:-1
 SetExternallyManagedOutroAnimation = <function> defined =[C]:-1
 SetToastDirection = <function> defined @FrameXML\QuickJoinToast.lua:133
 ToastToFriendAnim = <unnamed> {
 }
 wasShown = true
 groups = <table> {
 }
 UpdateDisplayedFriendCount = <function> defined @FrameXML\QuickJoinToast.lua:156
 GetHighestPriorityGroup = <function> defined @FrameXML\QuickJoinToast.lua:208
 FriendToToastAnim = <unnamed> {
 }
 Toast = <unnamed> {
 }
 FriendsButton = <unnamed> {
 }
 OnClick = <function> defined @FrameXML\QuickJoinToast.lua:303
 ProcessQueuedUpdates = <function> defined @FrameXML\QuickJoinToast.lua:93
 ToastActiveAnim = <unnamed> {
 }
 isOnRight = false
 OnShow = <function> defined @FrameXML\QuickJoinToast.lua:37
 QueueButton = <unnamed> {
 }
 ToastToFriendFinished = <function> defined @FrameXML\QuickJoinToast.lua:445
 throttle = <table> {
 }
 queuedUpdates = <table> {
 }
 groupsAwaitingDisplay = <table> {
 }
 Show = true
 QueueCount = <unnamed> {
 }
 FlashingLayer = <unnamed> {
 }
 UpdateQueueIcon = <function> defined @FrameXML\QuickJoinToast.lua:323
 ShouldSuppressAllToasts = <function> defined @FrameXML\QuickJoinToast.lua:231
 ToastToToastAnim = <unnamed> {
 }
 FriendCount = <unnamed> {
 }
 Toast2 = <unnamed> {
 }
 GetCurrentText = <function> defined @FrameXML\QuickJoinToast.lua:397
 OnManagedAlertFrameVisibilityChanged = <function> defined =[C]:-1
 HideToast = <function> defined @FrameXML\QuickJoinToast.lua:297
 ShouldDisplayGroup = <function> defined @FrameXML\QuickJoinToast.lua:256
 ToastToToastFinished = <function> defined @FrameXML\QuickJoinToast.lua:437
 CheckDisplayToast = <function> defined @FrameXML\QuickJoinToast.lua:190
 SetAlertContainer = <function> defined =[C]:-1
 OnMouseUp = <function> defined @FrameXML\QuickJoinToast.lua:318
 CheckShowToast = <function> defined @FrameXML\QuickJoinToast.lua:184
 ModifyToastDirection = <function> defined @FrameXML\QuickJoinToast.lua:139
 FriendToToastFinished = <function> defined @FrameXML\QuickJoinToast.lua:431
 SetCachedQueueData = <function> defined @FrameXML\QuickJoinToast.lua:389
 OnMouseDown = <function> defined @FrameXML\QuickJoinToast.lua:313
 HasCachedQueueData = <function> defined @FrameXML\QuickJoinToast.lua:381
 CachedQueueData = <function> defined @FrameXML\QuickJoinToast.lua:385
 ShowToast = <function> defined @FrameXML\QuickJoinToast.lua:265
 OnLoad = <function> defined @FrameXML\QuickJoinToast.lua:5
 OnEnter = <function> defined @FrameXML\QuickJoinToast.lua:347
 GetNextToastTime = <function> defined @FrameXML\QuickJoinToast.lua:235
 OnHide = <function> defined @FrameXML\QuickJoinToast.lua:44
 ClearCachedQueueData = <function> defined @FrameXML\QuickJoinToast.lua:393
 ToastPulse = <function> defined @FrameXML\QuickJoinToast.lua:423
 OnEvent = <function> defined @FrameXML\QuickJoinToast.lua:49
 QueueUpdate = <function> defined @FrameXML\QuickJoinToast.lua:89
 ProcessOrQueueUpdate = <function> defined @FrameXML\QuickJoinToast.lua:81
 GetAlertContainer = <function> defined =[C]:-1
 alertContainer = ChatAlertFrame {
 }
 OnPostHide = <function> defined =[C]:-1
 ManagesOwnOutroAnimation = <function> defined =[C]:-1
 ProcessUpdate = <function> defined @FrameXML\QuickJoinToast.lua:100
 SetTimerFor = <function> defined @FrameXML\QuickJoinToast.lua:162
}
(*temporary) = true
(*temporary) = QuickJoinToastButton {
 0 = <userdata>
 OnLeave = <function> defined @FrameXML\QuickJoinToast.lua:365
 OnPostShow = <function> defined =[C]:-1
 SetExternallyManagedOutroAnimation = <function> defined =[C]:-1
 SetToastDirection = <function> defined @FrameXML\QuickJoinToast.

**Comment by MarkKehn** [comment]
This is Mark_in_AJ from Curse by the way.  =)  Hi... again.  lol

EDIT: I don't know why this is referencing Friends and QuickJoins etc. I just started a new Alliance character on a new server, my first Alliance character in approximately 10-11 years. I don't use my Battletag name so no friends there, and since I am on a different faction than normal and also on a totally different realm server and Battlegroup I have yet to meet or make any in-game/server friends in the ten levels that I have been here so far.  /shrug

**Comment by LudiusMaximus** [comment]
Sorry, I did not see this earlier. But I think we resolved this already!

**Comment by LudiusMaximus** [comment]
Sorry, for not seeing this earlier. I think this might be resolved by now. Or are you still experiencing it?
