### ISSUE TITLE
Unused party frames pop up after combat

### ISSUE THREAD

**Issue by nang** [LudiusMaximus/Immersion_ExtraFade#4]
In Torghast, when solo, the addon is making party frames visible each time the combat ends (I make them go away repeatedly with /reload). 

This is happening whether or not the default UI setting "Use Raid-Style Party Frames" is enabled.

[https://imgur.com/jZcDgIX](url)

I determined cause by enabling individual addons iteratively.

**Comment by LudiusMaximus** [comment]
Thanks! Should be fixed with 1.13.3 now.
