### ISSUE TITLE
[ADDON_ACTION_BLOCKED] AddOn 'Immersion_ExtraFade' tried to call the protected function 'MainMenuBar:SetPointBase()'.

### ISSUE THREAD

**Issue by Ookami313** [LudiusMaximus/Immersion_ExtraFade#6]
Was pulled into combat and received the following error/popup that disabled my action bars (though I was able to mouse click the abilities). Error would keep occurring until I disabled to addon. Thanks.

1x [ADDON_ACTION_BLOCKED] AddOn 'Immersion_ExtraFade' tried to call the protected function 'MainMenuBar:SetPointBase()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:62: in function `SetPoint'
[string "@Interface/FrameXML/EditModeManager.lua"]:623: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:554: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@Interface/FrameXML/ActionBar.lua"]:350: in function `UpdateVisibility'
[string "@Interface/FrameXML/ActionBar.lua"]:317: in function `HideOverride'
[string "@Interface/FrameXML/ActionBar.lua"]:302: in function `SetShown'
[string "@Interface/FrameXML/StanceBar.lua"]:31: in function `Update'
[string "@Interface/FrameXML/ActionBarController.lua"]:131: in function `ActionBarController_UpdateAll'
[string "@Interface/FrameXML/ActionBarController.lua"]:66: in function <Interface/FrameXML/ActionBarController.lua:55>

**Comment by Fabricatedhero** [comment]
also getting this error

**Comment by LudiusMaximus** [comment]
Thanks for reporting. I was not able to reproduce this. I made some changes recently, which I don't know if they also resolved this issue. Please re-open this ticket, if it happens again. Ideally with a description of how to reproduce it.
