### ISSUE TITLE
10.1 issue

### ISSUE THREAD

**Issue by Mewohkie** [LudiusMaximus/Immersion_ExtraFade#8]
Message: Interface/AddOns/Immersion_ExtraFade/main.lua line 65:
   attempt to call field 'ShowUI' (a nil value)

Debug:
   [string "@Interface/AddOns/Immersion_ExtraFade/main.lua"]:65:
      Interface/AddOns/Immersion_ExtraFade/main.lua:47
Locals:
_ = Frame {
 0 = <userdata>
}
event = "PLAYER_ENTERING_WORLD"
(*temporary) = nil
(*temporary) = 0.500000
(*temporary) = false
(*temporary) = "attempt to call field 'ShowUI' (a nil value)"
Addon = <table> {
 uiHiddenTime = 0
}
fadeInTime = 0.500000

Message: Interface/AddOns/Immersion_ExtraFade/hide_module.lua line 336:
   hooksecurefunc(): AddBarFromTemplate is not a function

Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "@Interface/AddOns/Immersion_ExtraFade/hide_module.lua"]:336: in main chunk
Locals:

AddOns:
  Swatter, v9.1.BETA.5.11 (OneMawTime)
  AlterCurrencies, v0.1
  Auctioneer, v9.1.BETA.5.11 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.11 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.11 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.11 (OneMawTime)
  BagBrother, v
  Bagnon, v10.0.16
  CandyBuckets, v10.0.5.230128
  DBMCore, v35c800b
  DBMStatusBarTimers, v35c800b
  DBMVPVEM, vd743100
  Details, v#Details.DF.Wrath.10.0.7.10737.148-53-g3bc8ba7
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DynamicCam, v2.1.0
  Immersion, v1.4.22
  ImmersionExtraFade, v1.16.0
  SlideBar, v9.1.BETA.5.11 (OneMawTime)
  Stubby, v9.1.BETA.5.11 (OneMawTime)
  BlizRuntimeLib_enUS v10.1.0.100100 <none>
  (ck=31c)

**Comment by LudiusMaximus** [comment]
Thank you. Just released a new version with a fix.
