### ISSUE TITLE
LUA error after a cutscene

### ISSUE THREAD

**Issue by raysmith59** [LudiusMaximus/Immersion_ExtraFade#9]
I got this error immediately after the cutscene ended for the quest Morchie Mayhem.

1x Immersion_ExtraFade/main.lua:112: attempt to index global 'FramerateLabel' (a nil value)
[string "@Immersion_ExtraFade/main.lua"]:112: in function <Immersion_ExtraFade/main.lua:103>

Locals:
_ = Frame {
 0 = <userdata>
}
event = "CINEMATIC_STOP"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'FramerateLabel' (a nil value)"
cinematicRunning = false
framerateWasShown = false

**Comment by LudiusMaximus** [comment]
Thank you. I fixed this with the newest version 1.16.4.
